server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: auth_service
    password: changeit
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  flyway:
    enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://authorization-server/issuer

gateway:
  signature:
    secret: change-me

logging:
  level:
    org.springframework.security: INFO
